### ISSUE TITLE
使用CSS动画animation-play-state控制弹幕

### ISSUE THREAD

**Issue by jabbany** [jabbany/CommentCoreLibrary#21]
使用CSS动画animation-play-state控制弹幕实现暂停和播放。采取这个重新架构的话，很可能可以完全解除掉主定时器。

``` CSS
.paused{
    -webkit-animation-play-state:paused;
    -moz-animation-play-state:paused;
    -o-animation-play-state:paused; 
    animation-play-state:paused;
}
```

动态添加删除类的话。相关技术有待在新的分支下进行研究。有关纯CSS3和Canvas性能的对比也尚未完全进行。

关联参考：
http://stackoverflow.com/questions/5804444/how-to-pause-and-resume-css3-animation-using-javascript
https://developer.mozilla.org/en-US/docs/Web/CSS/animation-play-state

兼容性：
- Chrome，Safari（Webkit系）：最新版 
- Gecko（Firefox）：5+
- IE：10+
- Opera：12+
